# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Glo Networks
org_slug: GlodoUK
rebel_module_groups: []
repo_description: ' Odoo server side related addons '
repo_name: Server, or system, level related modules for Odoo
repo_slug: server-tools
repo_website: https://github.com/GlodoUK/server-tools
travis_apt_packages: []
travis_apt_sources: []

