{
    "version": "13.0.1.0.0",
    "name": "healthcheck",
    "summary": """Healthcheck for monitoring, etc. Complementary to prometheus module.""",
    "category": "Other",
    "images": [],
    "application": False,
    "author": "Glo Networks",
    "website": "https://www.glo.systems/",
    "license": "Other proprietary",
    "depends": ["web"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
    "description": """Healthcheck for monitoring, etc. Complementary to prometheus module.""",
}
