{
    "version": "12.0.1.0.0",
    "name": "with_savepoint_exception",
    "summary": "Technical module that provides a with_savepoint_exception decorator",
    "category": "Hidden",
    "images": [],
    "application": True,
    "author": "Glo Networks",
    "website": "https://glo.systems/",
    "license": "Other proprietary",
    "depends": ["onchange_helper"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
